name: instagramish
description: A library that includes instagramish ui components.
version: 0.1.0
homepage: https://github.com/HeavenOSK/flutter_instagramish
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: